// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD44-6C7lrP9aekCmu9UjkgIQmBzLceoDM',
    appId: '1:965958270577:web:913dd968740a13486b65d0',
    messagingSenderId: '965958270577',
    projectId: 'gsc2k23',
    authDomain: 'gsc2k23.firebaseapp.com',
    storageBucket: 'gsc2k23.appspot.com',
    measurementId: 'G-WEXM07VQYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChddHz1_AGfQiIxKrUzNINproPk_gB2xA',
    appId: '1:965958270577:android:de6114e572f1ca376b65d0',
    messagingSenderId: '965958270577',
    projectId: 'gsc2k23',
    storageBucket: 'gsc2k23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0ZepLEvsNB80pnugyLsokDFdtfnFx4M',
    appId: '1:965958270577:ios:453f0b01a75111546b65d0',
    messagingSenderId: '965958270577',
    projectId: 'gsc2k23',
    storageBucket: 'gsc2k23.appspot.com',
    androidClientId: '965958270577-5b61qalqcucasnq74j7h3skiq3q63s65.apps.googleusercontent.com',
    iosClientId: '965958270577-b4dnqkbet84jbdg1bqkp56iv0vjar31t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0ZepLEvsNB80pnugyLsokDFdtfnFx4M',
    appId: '1:965958270577:ios:453f0b01a75111546b65d0',
    messagingSenderId: '965958270577',
    projectId: 'gsc2k23',
    storageBucket: 'gsc2k23.appspot.com',
    androidClientId: '965958270577-5b61qalqcucasnq74j7h3skiq3q63s65.apps.googleusercontent.com',
    iosClientId: '965958270577-b4dnqkbet84jbdg1bqkp56iv0vjar31t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
